### PR TITLE
fixed typo - owrk to work

### PR DESCRIPTION
**Pull request by digininja**
fixed typo - owrk to work

### CODE REVIEW

**Comment by PrometheanInfoSec** [comment]
Lol, thanks man.

**Comment by digininja** [comment]
Always supporting the community :)

**Comment by PrometheanInfoSec** [comment]
Do you want me to add you to the list of contributors?  I can make a field for "minor contributors" as a thank you for your time spent on the fork over my typo.

**Comment by digininja** [comment]
I'll pass thanks, it is enough to know myself that I played my part :)

**Pull request merged**
